version: 2.1

jobs:
  build:
    docker:
      - image: emscripten/emsdk:2.0.2
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: "apt update && apt install -y libtool"
      - run:
          name: "Make"
          command: "make"
      - store_artifacts:
          path: ~/project/dist

workflows:
  build:
    jobs:
      - build
